version: "3"

services:
  server:
    image: blackkiwi-puppeteer:0.0.1
    container_name: puppeteer
    volumes:
      - ./:/app/
    restart: always
    ports:
      - "3000:3000"
    working_dir: /app/
    user: root
    command: bash -c "chmod +x ./scripts/init.sh && ./scripts/init.sh"
    environment:
      TZ: "Asia/Seoul"
